2.0.0
rreinold/real_time_asset_tracking_template pull request #1
Opened 2018-05-18 22:19 UTC by rreinold

basically a rewrite

2018-05-21 20:43 UTC, yashjain28 requested changes

2018-05-21 20:43 UTC, yashjain28 commented on Readme.md
> +- `CJS_Portal` - Holistic view of your Real-Time Asset Tracking System, with a 3D Map of Tags
Please conform to portal case conventions PascalCase

2018-05-21 20:43 UTC, yashjain28 commented on Readme.md
>  ### Collections
Please conform to collection case conventions snake_case

2018-05-21 20:43 UTC, yashjain28 commented on Readme.md
>  ### Triggers
Please conform to Trigger case conventions PascalCase

2018-05-21 20:43 UTC, yashjain28 commented on Readme.md
> +### How to Update Graph
Isn't the API section the last one, or it's fine to add credits in this one?

2018-05-21 20:43 UTC, yashjain28 commented on .gitignore
> +.cbmeta
jsdoc.md
We should not be uploading jsdoc.md file.

2018-05-21 20:43 UTC, yashjain28 commented on data/Tags.json
> -            "payload": "Disabled",
Not sure if you want to upload all the data. That's unwanted information.

2018-05-21 20:43 UTC, yashjain28 commented on Readme.md
> +## RTAssetCheckGeofence()
All these functions are under API so should be ### or even ####
These are very big headings if you take a look at the readme.

2018-05-21 20:43 UTC, yashjain28 commented on Readme.md
> +## Functions
functions are inside API shouldn't it be ###

2018-05-21 20:43 UTC, yashjain28 commented on package.json
> -    "test": "echo \"Error: no test specified\" && exit 1"
Really liked this idea. Good one. But let me know if you just want to do Libraries now or maybe with params, like 
npm run jsdoc -services
npm run jsdoc -libraries
npm run jsdoc -all
https://stackoverflow.com/questions/35221098/passing-arguments-to-npm-script-in-package-json

2018-05-21 20:50 UTC, rreinold commented on Readme.md
>  ### Collections
these are message topics

2018-05-21 21:18 UTC, rreinold commented on Readme.md
> +- `CJS_Portal` - Holistic view of your Real-Time Asset Tracking System, with a 3D Map of Tags
e0c0342

2018-05-21 21:33 UTC, rreinold commented on Readme.md
>  ### Collections
6d8e719

2018-05-21 21:33 UTC, rreinold commented on Readme.md
>  ### Triggers
da41052

2018-05-21 21:34 UTC, rreinold commented on data/Tags.json
> -            "payload": "Disabled",
This data is displayed in the Portal OOB

2018-05-21 21:52 UTC, rreinold commented on .gitignore
> +.cbmeta
cfb0ff16c336566be8bc00a9eda3ef697f9f2ec8

2018-05-21 21:54 UTC, rreinold commented on package.json
> -    "test": "echo \"Error: no test specified\" && exit 1"
this one needs to jsdoc all, we'll tackle the flag on the next one

2018-05-21 21:54 UTC, rreinold commented
addressed issues

2018-05-21 22:42 UTC, yashjain28 commented on package.json
> -    "test": "echo \"Error: no test specified\" && exit 1"
Np

2018-05-21 22:49 UTC, yashjain28 commented
Just one change and it can be merged then.

2018-05-21 22:54 UTC, yashjain28 commented on data/Tags.json
> -            "payload": "Disabled",
Np

2018-05-21 23:03 UTC, yashjain28 commented on Readme.md
> +- `CJS_Portal` - Holistic view of your Real-Time Asset Tracking System, with a 3D Map of Tags
Rename in Readme CJS_Portal and Triggers section

2018-05-21 23:10 UTC, yashjain28 requested changes
A couple of small changes. 
Just a heads up. We need to make changes in the roles (and portals also if we're using it there) if we rename a service. And if rename a lib then servicesName.json needs to be changed for dependencies.

2018-05-22 14:27 UTC, rreinold commented
Roles updated 4223aeeafc29718110ca6e6b13258fdf5f9545b8

2018-05-22 14:28 UTC, rreinold commented
e1102a0 Finished rename of portal

2018-05-22 14:38 UTC, merged